import fs from "node:fs/promises";
import path from "node:path";
import { build, type BuildOptions } from "esbuild";
import { createIndexHtml } from "./create-index-html";
import { collectExamplesByEntry } from "./example-extractor";
import { DIST_DIR, readBooleanEnv, readEnv, type RootEntry } from "./config";
import { discoverRootEntries } from "./discover-entries";

const GLOBAL_NAMESPACE = readEnv("BUILD_GLOBAL_NAMESPACE", "Rod");
const SHOULD_WRITE_META = readBooleanEnv("BUILD_META", true);

export async function main(): Promise<void> {
  await fs.rm(DIST_DIR, { recursive: true, force: true });
  await fs.mkdir(DIST_DIR, { recursive: true });

  const entries = await discoverRootEntries();
  if (entries.length === 0) {
    throw new Error("No root entrypoints found in src/. Add src/broto.ts, src/fabrica.ts, src/fabrica-elements.ts, src/cipo.ts, or src/index.ts.");
  }

  const outputs: string[] = [];
  for (const entry of entries) {
    outputs.push(...(await buildEntry(entry)));
  }

  const examples = await collectExamplesByEntry(entries);
  const manifest = createManifest(entries, outputs);
  await fs.writeFile(path.join(DIST_DIR, "manifest.json"), JSON.stringify({ ...manifest, examples }, null, 2));
  await fs.writeFile(path.join(DIST_DIR, "index.html"), createIndexHtml({ entries, outputs, namespace: GLOBAL_NAMESPACE, examples }));
}

async function buildEntry(entry: RootEntry): Promise<string[]> {
  const banner = createBanner(entry);
  const baseOptions: BuildOptions = {
    entryPoints: [entry.absolutePath],
    bundle: true,
    platform: "browser",
    target: ["es2022"],
    jsx: "automatic",
    legalComments: "inline",
    sourcemap: true,
    charset: "utf8",
    logLevel: "info",
    metafile: SHOULD_WRITE_META,
    banner: { js: banner },
    define: {
      "process.env.NODE_ENV": JSON.stringify("production"),
    },
  };

  const normalIife = path.join(DIST_DIR, `${entry.name}.iife.js`);
  const minIife = path.join(DIST_DIR, `${entry.name}.iife.min.js`);
  const normalEsm = path.join(DIST_DIR, `${entry.name}.esm.js`);
  const minEsm = path.join(DIST_DIR, `${entry.name}.esm.min.js`);

  const results = await Promise.all([
    build({ ...baseOptions, format: "iife", globalName: entry.globalName, outfile: normalIife, minify: false }),
    build({ ...baseOptions, format: "iife", globalName: entry.globalName, outfile: minIife, minify: true }),
    build({ ...baseOptions, format: "esm", outfile: normalEsm, minify: false }),
    build({ ...baseOptions, format: "esm", outfile: minEsm, minify: true }),
  ]);

  if (SHOULD_WRITE_META) {
    await Promise.all(
      results.map((result, index) => fs.writeFile(path.join(DIST_DIR, `${entry.name}.${index}.meta.json`), JSON.stringify(result.metafile, null, 2))),
    );
  }

  return [normalIife, minIife, normalEsm, minEsm].map((file) => path.relative(DIST_DIR, file));
}

function createBanner(entry: RootEntry): string {
  const description = entry.tool.description.replace(/\*\//g, "*");
  return `/**\n * @tool ${entry.tool.name}\n * @global ${entry.globalName}\n * @entry ${entry.relativePath}\n * @description ${description}\n * @generated by Rod root IIFE build system\n */`;
}

function createManifest(entries: RootEntry[], outputs: string[]): Record<string, unknown> {
  return {
    generatedAt: new Date().toISOString(),
    namespace: GLOBAL_NAMESPACE,
    entries: entries.map((entry) => ({
      name: entry.name,
      globalName: entry.globalName,
      entry: entry.relativePath,
      description: entry.tool.description,
      tags: entry.tool.tags,
      files: outputs.filter((output) => output.startsWith(`${entry.name}.`)),
    })),
  };
}

await main();
