import fs from "node:fs/promises";
import path from "node:path";
import { glob } from "node:fs/promises";
import { build } from "esbuild";

import {
  DEFAULT_ENTRYPOINT,
  DEFAULT_GLOBAL_NAME,
  DIST_DIR,
  readBooleanEnv,
  readEnv,
} from "./config";

const entrypoint = readEnv("BUILD_ENTRYPOINT", DEFAULT_ENTRYPOINT);
const globalName = readEnv("BUILD_GLOBAL_NAME", DEFAULT_GLOBAL_NAME);
const minify = readBooleanEnv("BUILD_MINIFY", true);

/**
 * Builds bundled browser artifacts and individual module files.
 *
 * @returns A promise that resolves after all output files are written.
 *
 * @example
 * ```ts
 * await main();
 * // dist/bundle.esm.js, dist/bundle.iife.js, and individual modules are created.
 * ```
 */
async function main(): Promise<void> {
  await fs.rm(DIST_DIR, { recursive: true, force: true });
  await fs.mkdir(DIST_DIR, { recursive: true });

  await build({
    entryPoints: [entrypoint],
    outfile: path.join(DIST_DIR, "bundle.esm.js"),
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    sourcemap: true,
    minify,
    legalComments: "none",
    logLevel: "info",
  });

  await build({
    entryPoints: [entrypoint],
    outfile: path.join(DIST_DIR, "bundle.iife.js"),
    bundle: true,
    format: "iife",
    globalName,
    platform: "browser",
    target: "es2022",
    sourcemap: true,
    minify,
    legalComments: "none",
    logLevel: "info",
  });

  const entryPoints = await collectModuleEntryPoints();

  const result = await build({
    entryPoints,
    outdir: DIST_DIR,
    outbase: "src",
    bundle: false,
    format: "esm",
    platform: "browser",
    target: "es2022",
    sourcemap: true,
    minify,
    legalComments: "none",
    metafile: true,
    write: true,
    logLevel: "info",
  });

  const outputs = Object.keys(result.metafile.outputs);

  await fs.writeFile(
    path.join(DIST_DIR, "metafile-outputs.json"),
    JSON.stringify(outputs, null, 2),
    "utf8",
  );

  await fs.writeFile(
    path.join(DIST_DIR, "release-assets.txt"),
    outputs.join("\n"),
    "utf8",
  );

  await fs.writeFile(
    path.join(DIST_DIR, "index.html"),
    createIndexHtml(globalName, outputs),
    "utf8",
  );

  console.log(`✅ Built private TypeScript entrypoint: ${entrypoint}`);
  console.log(`📦 ESM:  ${path.join(DIST_DIR, "bundle.esm.js")}`);
  console.log(`🌍 IIFE: ${path.join(DIST_DIR, "bundle.iife.js")} as window.${globalName}`);

  for (const output of outputs) {
    console.log(`📦 FILE: ${output}`);
  }
}

/**
 * Collects every TypeScript source file except the root src/index.ts entrypoint.
 *
 * @returns Source files that should be emitted as individual modules.
 *
 * @example
 * ```ts
 * const files = await collectModuleEntryPoints();
 * // ["src/logger.ts", "src/utils/index.ts"]
 * ```
 */
async function collectModuleEntryPoints(): Promise<string[]> {
  const files: string[] = [];

  for await (const file of glob("src/**/*.ts")) {
    if (file === "src/index.ts") {
      continue;
    }

    files.push(file);
  }

  return files;
}

/**
 * Creates a tiny GitHub Pages landing page for generated browser artifacts.
 *
 * @param globalName - Name exposed by the IIFE build.
 * @param outputs - Output files generated by esbuild.
 * @returns HTML content for dist/index.html.
 *
 * @example
 * ```ts
 * createIndexHtml("FabricaHTML", ["dist/button.js"]);
 * // "<!doctype html>..."
 * ```
 */
function createIndexHtml(globalName: string, outputs: string[]): string {
  const moduleLinks = outputs
    .filter((output) => output.endsWith(".js"))
    .map((output) => {
      const href = output.startsWith(`${DIST_DIR}/`)
        ? output.slice(DIST_DIR.length + 1)
        : output;

      return `<p>${href}: <a href="./${href}" target="_blank" rel="noreferrer">${href}</a></p>`;
    })
    .join("\n");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Private TS Bundle</title>
    <style>
      body { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 2rem; background: #0b1020; color: #f8fafc; }
      code { background: #111827; padding: .2rem .4rem; border-radius: .4rem; }
      a { color: #93c5fd; }
    </style>
  </head>
  <body>
    <h1>Private TS Bundle</h1>
    <p>ESM: <a href="./bundle.esm.js">bundle.esm.js</a></p>
    <p>IIFE: <a href="./bundle.iife.js">bundle.iife.js</a></p>
    <p>Global name: <code>window.${globalName}</code></p>
    <h2>Individual modules</h2>
    ${moduleLinks}
  </body>
</html>`;
}

await main();
