import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

export interface BuildMetadata {
  readonly sha: string;
  readonly shortSha: string;
  readonly builtAt: string;
  readonly builtAtGmtMinus3: string;
  readonly buildDateShort: string;
  readonly buildTimeShort: string;
  readonly timezone: "GMT-3";
  readonly mode: string;
  readonly version: string;
}

export interface CreateBuildMetadataOptions {
  readonly root: string;
  readonly version?: string;
  readonly mode?: string;
  readonly now?: Date;
  readonly sha?: string;
}

export interface IifeBannerDetails {
  readonly tool?: string;
  readonly globalName?: string;
  readonly entry?: string;
  readonly description?: string;
  readonly generatedBy?: string;
}

/** Resolves the full build commit from CI first and Git as a local fallback. */
export function resolveBuildCommit(root: string): {
  readonly full: string;
  readonly short: string;
} {
  const full =
    process.env.RODERUDA_BUILD_SHA?.trim()
    || process.env.GITHUB_SHA?.trim()
    || readGitCommit(root);

  return {
    full,
    short: full === "development" ? "dev" : full.slice(0, 7),
  };
}

/** Reads the root package version without making Vite configs duplicate IO. */
export function readPackageVersion(root: string): string {
  try {
    const packageJson = JSON.parse(
      readFileSync(resolve(root, "package.json"), "utf8"),
    ) as { version?: string };

    return packageJson.version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

/** Creates one canonical build metadata payload in the GMT-3 product timezone. */
export function createBuildMetadata(
  options: CreateBuildMetadataOptions,
): BuildMetadata {
  const now = options.now ?? new Date();
  const commit = options.sha
    ? {
        full: options.sha,
        short: options.sha === "development" ? "dev" : options.sha.slice(0, 7),
      }
    : resolveBuildCommit(options.root);

  const parts = new Intl.DateTimeFormat("pt-BR", {
    timeZone: "America/Sao_Paulo",
    day: "2-digit",
    month: "2-digit",
    year: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).formatToParts(now);

  const value = (type: Intl.DateTimeFormatPartTypes): string =>
    parts.find((part) => part.type === type)?.value ?? "";

  const date = `${value("day")}/${value("month")}/${value("year")}`;
  const time = `${value("hour")}:${value("minute")}`;

  return {
    sha: commit.full,
    shortSha: commit.short,
    builtAt: now.toISOString(),
    builtAtGmtMinus3: `${date} ${time} GMT-3`,
    buildDateShort: date,
    buildTimeShort: time,
    timezone: "GMT-3",
    mode: options.mode ?? process.env.NODE_ENV ?? "prod",
    version: options.version ?? "0.0.0",
  };
}

/** Creates a stable preserved banner for generated IIFE browser bundles. */
export function createIifeBuildBanner(
  metadata: BuildMetadata,
  details: IifeBannerDetails = {},
): string {
  const lines = [
    `Built: ${metadata.builtAtGmtMinus3}`,
    `Commit: ${metadata.sha}`,
    details.tool ? `@tool ${sanitizeBannerValue(details.tool)}` : "",
    details.globalName ? `@global ${sanitizeBannerValue(details.globalName)}` : "",
    details.entry ? `@entry ${sanitizeBannerValue(details.entry)}` : "",
    details.description
      ? `@description ${sanitizeBannerValue(details.description)}`
      : "",
    details.generatedBy
      ? `@generated by ${sanitizeBannerValue(details.generatedBy)}`
      : "",
  ].filter(Boolean);

  return `/**\n${lines.map((line) => ` * ${line}`).join("\n")}\n */`;
}

function readGitCommit(root: string): string {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: root,
      encoding: "utf8",
    }).trim();
  } catch {
    return "development";
  }
}

function sanitizeBannerValue(value: string): string {
  return value.replace(/\*\//g, "*").replace(/\r?\n/g, " ").trim();
}
