export type DocsExample = {
  title: string;
  language: string;
  code: string;
  source: string;
};

/**
 * Creates the landing page for generated browser artifacts and docs examples.
 *
 * @param globalName - Name exposed by the IIFE build.
 * @param outputs - Output files generated by esbuild.
 * @returns HTML content for dist/index.html.
 *
 * @example
 * ```ts
 * const html = createIndexHtml("Seiva", ["dist/bundle.esm.js"], []);
 * console.log(html.includes("bundle.esm.js"));
 * // true
 * ```
 */
export function createIndexHtml(
  globalName: string,
  outputs: string[],
  examples: DocsExample[],
): string {
  const moduleLinks = createModuleLinks(outputs);
  const exampleBlocks = createExampleBlocks(examples);

  return `<!doctype html>
<html lang="en">
${createHead()}
  <body>
    <main>
      <section class="hero">
        <h1>Private TS Bundle</h1>
        <p>ESM: <a href="./bundle.esm.js">bundle.esm.js</a></p>
        <p>IIFE: <a href="./bundle.iife.js">bundle.iife.js</a></p>
        <p>Global name: <code>window.${escapeHtml(globalName)}</code></p>
      </section>

      <section>
        <h2>Individual modules</h2>
        ${moduleLinks}
      </section>

      <section>
        <h2>Examples</h2>
        ${exampleBlocks || "<p>No TSDoc examples found.</p>"}
      </section>
    </main>
  </body>
</html>`;
}

/**
 * Creates the document head with styles and syntax highlighting assets.
 *
 * @returns HTML head markup.
 *
 * @example
 * ```ts
 * const head = createHead();
 * console.log(head.includes("highlight.min.js"));
 * // true
 * ```
 */
function createHead(): string {
  return `  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Private TS Bundle</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/javascript.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/typescript.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/html.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/css.min.js"></script>
    <script>hljs.highlightAll();</script>
    <style>
${createStyles()}

/*!
  Theme: Material Darker
  Author: Nate Peterson
  License: ~ MIT (or more permissive) [via base16-schemes-source]
  Maintainer: @highlightjs/core-team
  Version: 2021.09.0
*/
pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}
code.hljs {
  padding: 3px 5px;
}
.hljs {
  color: #eff;
  background: var(--package-accent);
}
.hljs ::selection,
.hljs::selection {
  background-color: #353535;
  color: #eff;
}
.hljs-comment {
  color: #4a4a4a;
}
.hljs-tag {
  color: #b2ccd6;
}
.hljs-operator,
.hljs-punctuation,
.hljs-subst {
  color: #eff;
}
.hljs-operator {
  opacity: 0.7;
}
.hljs-bullet,
.hljs-deletion,
.hljs-name,
.hljs-selector-tag,
.hljs-template-variable,
.hljs-variable {
  color: #f07178;
}
.hljs-attr,
.hljs-link,
.hljs-literal,
.hljs-number,
.hljs-symbol,
.hljs-variable.constant_ {
  color: #f78c6c;
}
.hljs-class .hljs-title,
.hljs-title,
.hljs-title.class_ {
  color: #ffcb6b;
}
.hljs-strong {
  font-weight: 700;
  color: #ffcb6b;
}
.hljs-addition,
.hljs-code,
.hljs-string,
.hljs-title.class_.inherited__ {
  color: #c3e88d;
}
.hljs-built_in,
.hljs-doctag,
.hljs-keyword.hljs-atrule,
.hljs-quote,
.hljs-regexp {
  color: #89ddff;
}
.hljs-attribute,
.hljs-function .hljs-title,
.hljs-section,
.hljs-title.function_,
.ruby .hljs-property {
  color: #82aaff;
}
.diff .hljs-meta,
.hljs-keyword,
.hljs-template-tag,
.hljs-type {
  color: #c792ea;
}
.hljs-emphasis {
  color: #c792ea;
  font-style: italic;
}
.hljs-meta,
.hljs-meta .hljs-keyword,
.hljs-meta .hljs-string {
  color: #ff5370;
}
.hljs-meta .hljs-keyword,
.hljs-meta-keyword {
  font-weight: 700;
}

    </style>
  </head>`;
}

/**
 * Creates all CSS used by the generated landing page.
 *
 * @returns CSS content.
 *
 * @example
 * ```ts
 * const css = createStyles();
 * console.log(css.includes("--package-accent"));
 * // true
 * ```
 */
function createStyles(): string {
  return `      :root {
        --package-accent: #111113;
        --pre-bg: color-mix(in srgb, var(--package-accent) 29%, black);
      }

      body {
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        margin: 0;
        background: #09090b;
        color: #f8fafc;
      }

      main {
        max-width: 980px;
        margin: 0 auto;
        padding: 32px 18px 72px;
      }

      a {
        color: #93c5fd;
      }

      .hero {
        padding: 28px;
        border: 1px solid #27272a;
        border-radius: 24px;
        background:
          radial-gradient(circle at top left, rgba(148, 163, 184, 0.14), transparent 34rem),
          #111113;
      }

      [data-package="seivastate"] {
        --package-accent: #116613;
      }

      .example-card {
        margin-top: 18px;
        border: 1px solid #27272a;
        border-radius: 18px;
        overflow: hidden;
        background: var(--package-accent);
      }

      .example-header {
        display: flex;
        justify-content: space-between;
        gap: 16px;
        padding: 14px 16px;
        border-bottom: 1px solid #27272a;
      }

      .example-header h3 {
        margin: 0;
        font-size: 15px;
      }

      .example-header span {
        color: #a1a1aa;
        font-size: 12px;
      }

      pre {
        margin: 0;
        padding: 16px;
        overflow: auto;
        background: var(--pre-bg);
      }

      code {
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 13px;
        line-height: 1.7;
      }`;
}

/**
 * Creates links for every generated JavaScript module.
 *
 * @param outputs - Output files generated by esbuild.
 * @returns HTML links for generated modules.
 *
 * @example
 * ```ts
 * const links = createModuleLinks(["dist/seiva.js", "dist/seiva.js.map"]);
 * console.log(links);
 * // '<p><a href="./seiva.js">seiva.js</a></p>'
 * ```
 */
function createModuleLinks(outputs: string[]): string {
  return outputs
    .filter((output) => output.endsWith(".js"))
    .map((output) => {
      const href = normalizeDistHref(output);

      return `<p><a href="./${escapeHtml(href)}">${escapeHtml(href)}</a></p>`;
    })
    .join("\n");
}

/**
 * Creates article cards for extracted TSDoc examples.
 *
 * @param examples - Extracted examples ready for docs rendering.
 * @returns HTML cards.
 *
 * @example
 * ```ts
 * const html = createExampleBlocks([
 *   { title: "Basic usage", language: "ts", code: "hello()", source: "src/seiva-state.ts" },
 * ]);
 *
 * console.log(html.includes('data-package="seivastate"'));
 * // true
 * ```
 */
function createExampleBlocks(examples: DocsExample[]): string {
  return examples
    .map((example) => {
      const packageName = normalizeSourcePackageName(example.source);

      return `
        <article class="example-card" data-package="${escapeHtml(packageName)}">
          <div class="example-header">
            <h3>${escapeHtml(example.title)}</h3>
            <span>${escapeHtml(example.source)}</span>
          </div>
          <pre><code class="language-${escapeHtml(example.language)}">${escapeHtml(example.code)}</code></pre>
        </article>
      `;
    })
    .join("\n");
}

/**
 * Normalizes dist paths into browser-friendly relative hrefs.
 *
 * @param output - Raw esbuild output path.
 * @returns Path without a leading dist segment.
 *
 * @example
 * ```ts
 * normalizeDistHref("dist/seiva.js");
 * // "seiva.js"
 *
 * normalizeDistHref("/dist/seiva.js");
 * // "seiva.js"
 * ```
 */
function normalizeDistHref(output: string): string {
  return output.replace(/^\/?dist\/?/, "");
}

/**
 * Normalizes a source file path into a package bucket name.
 *
 * @param source - Source file path.
 * @returns Lowercase package name without extension, accents, numbers, spaces, or special characters.
 *
 * @example
 * ```ts
 * normalizeSourcePackageName("src/seiva-state.ts");
 * // "seivastate"
 *
 * normalizeSourcePackageName("src/Fábrica.HTML.ts");
 * // "fabricahtml"
 * ```
 */
function normalizeSourcePackageName(source: string): string {
  return source
    .split("/")
    .pop()
    ?.normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-zA-Z]/g, "")
    .toLowerCase() ?? "";
}

/**
 * Escapes HTML-sensitive characters for safe landing page rendering.
 *
 * @param value - Raw string value.
 * @returns HTML-safe text.
 *
 * @example
 * ```ts
 * escapeHtml("<script>");
 * // "&lt;script&gt;"
 * ```
 */
function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => {
    switch (character) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      case "'":
        return "&#39;";
      default:
        return character;
    }
  });
}
