/**
 * Nascente is a zero-dependency, allocation-conscious utility toolkit optimized for hot paths.
 *
 * @remarks
 * Performance strategy: plain indexed loops for dense arrays, single-pass transforms, lazy allocation,
 * `Set`/`Map` membership where asymptotically useful, and no iterator/intermediate-array pipelines in hot paths.
 * Safari/WebKit benefits especially from predictable monomorphic loops and fewer short-lived allocations.
 * Always benchmark with your real data: native engines evolve and tiny inputs may favor built-ins.
 *
 * @packageDocumentation
 */

export type Iteratee<T, R> = (value: T, index: number) => R;
export type Predicate<T> = (value: T, index: number) => unknown;
export type Comparator<T> = (a: T, b: T) => boolean;
export type Awaitable<T> = T | PromiseLike<T>;

/** Fast indexed replacement for `Array.prototype.at`. @remarks Avoids method dispatch and normalizes negative indexes directly. Use `at(array, -1)`. */
export function at<T>(a: ArrayLike<T>, i: number): T | undefined { i=i<0?a.length+i:i; return i>=0&&i<a.length?a[i]:undefined; }
/** Single-pass replacement for repeated `slice` chunking. @remarks Pre-sizes output chunks and avoids callback allocations. */
export function chunk<T>(a: readonly T[], n=1): T[][] { n=Math.max(1,n|0); const out:T[][]=[]; for(let i=0;i<a.length;i+=n) out.push(a.slice(i,i+n)); return out; }
export function compact<T>(a: readonly T[]): NonNullable<T>[] { const o:NonNullable<T>[]=[]; for(let i=0;i<a.length;i++) if(a[i]) o.push(a[i] as NonNullable<T>); return o; }
export function head<T>(a: readonly T[]):T|undefined{return a[0]} export function last<T>(a:readonly T[]):T|undefined{return a[a.length-1]}
export function initial<T>(a:readonly T[]):T[]{return a.slice(0,-1)} export function tail<T>(a:readonly T[]):T[]{return a.slice(1)}
export function take<T>(a:readonly T[],n=1):T[]{return a.slice(0,n<0?0:n)} export function takeRight<T>(a:readonly T[],n=1):T[]{return a.slice(Math.max(0,a.length-n))}
export function drop<T>(a:readonly T[],n=1):T[]{return a.slice(Math.max(0,n))} export function dropRight<T>(a:readonly T[],n=1):T[]{return a.slice(0,Math.max(0,a.length-n))}
export function takeWhile<T>(a:readonly T[],p:Predicate<T>):T[]{let i=0;while(i<a.length&&p(a[i]!,i))i++;return a.slice(0,i)}
export function takeRightWhile<T>(a:readonly T[],p:Predicate<T>):T[]{let i=a.length-1;while(i>=0&&p(a[i]!,i))i--;return a.slice(i+1)}
export function dropWhile<T>(a:readonly T[],p:Predicate<T>):T[]{let i=0;while(i<a.length&&p(a[i]!,i))i++;return a.slice(i)}
export function dropRightWhile<T>(a:readonly T[],p:Predicate<T>):T[]{let i=a.length-1;while(i>=0&&p(a[i]!,i))i--;return a.slice(0,i+1)}
/** Allocation-light replacement for `array.map(...).flat()`. @remarks Fuses mapping and flattening into one pass, avoiding the intermediate mapped array. */
export function flatMap<T,R>(a:readonly T[],fn:Iteratee<T,R|readonly R[]>):R[]{const o:R[]=[];for(let i=0;i<a.length;i++){const v=fn(a[i]!,i);Array.isArray(v)?o.push(...v as R[]):o.push(v as R)}return o}
export function flatten<T>(a:readonly (T|readonly T[])[]):T[]{const o:T[]=[];for(let i=0;i<a.length;i++){const v=a[i]!;Array.isArray(v)?o.push(...v as T[]):o.push(v as T)}return o}
export function flattenDeep<T>(a:readonly unknown[]):T[]{const o:T[]=[];const s=[...a].reverse();while(s.length){const v=s.pop();if(Array.isArray(v))for(let i=v.length-1;i>=0;i--)s.push(v[i]);else o.push(v as T)}return o}
export function flatMapDeep<T,R>(a:readonly T[],fn:Iteratee<T,unknown>):R[]{const mapped:unknown[]=[];for(let i=0;i<a.length;i++)mapped.push(fn(a[i]!,i));return flattenDeep<R>(mapped)}
/** Faster hot-path alternative to `Array.prototype.map` when async work is needed. @remarks Pre-allocates result storage; `concurrency` avoids unbounded `Promise.all` pressure on mobile. */
export async function mapAsync<T,R>(a:readonly T[],fn:(v:T,i:number)=>Awaitable<R>,concurrency=Infinity):Promise<R[]>{const o=new Array<R>(a.length);await limitAsync(a,async(v,i)=>{o[i]=await fn(v,i)},concurrency);return o}
export async function filterAsync<T>(a:readonly T[],fn:(v:T,i:number)=>Awaitable<unknown>,concurrency=Infinity):Promise<T[]>{const keep=await mapAsync(a,fn,concurrency);const o:T[]=[];for(let i=0;i<a.length;i++)if(keep[i])o.push(a[i]!);return o}
export async function flatMapAsync<T,R>(a:readonly T[],fn:(v:T,i:number)=>Awaitable<R|readonly R[]>,c=Infinity):Promise<R[]>{return flatten(await mapAsync(a,fn,c))}
export async function forEachAsync<T>(a:readonly T[],fn:(v:T,i:number)=>Awaitable<unknown>,c=Infinity):Promise<void>{await limitAsync(a,fn,c)}
export async function limitAsync<T>(a:readonly T[],fn:(v:T,i:number)=>Awaitable<unknown>,c=Infinity):Promise<void>{c=Math.max(1,Math.min(a.length,c|0||a.length));let next=0;async function worker(){for(;;){const i=next++;if(i>=a.length)return;await fn(a[i]!,i)}}await Promise.all(Array.from({length:c},worker))}
export async function reduceAsync<T,R>(a:readonly T[],fn:(acc:R,v:T,i:number)=>Awaitable<R>,acc:R):Promise<R>{for(let i=0;i<a.length;i++)acc=await fn(acc,a[i]!,i);return acc}
export function forEachRight<T>(a:readonly T[],fn:(v:T,i:number)=>void):void{for(let i=a.length-1;i>=0;i--)fn(a[i]!,i)}
/** One-pass grouping replacement for `Object.groupBy` plus post-processing. @remarks Uses a null-prototype object to avoid prototype collisions and extra safety checks. */
export function groupBy<T>(a:readonly T[],fn:(v:T,i:number)=>PropertyKey):Record<PropertyKey,T[]>{const o=Object.create(null) as Record<PropertyKey,T[]>;for(let i=0;i<a.length;i++){const k=fn(a[i]!,i);(o[k]??=[]).push(a[i]!)}return o}
export function keyBy<T>(a:readonly T[],fn:(v:T,i:number)=>PropertyKey):Record<PropertyKey,T>{const o=Object.create(null) as Record<PropertyKey,T>;for(let i=0;i<a.length;i++)o[fn(a[i]!,i)]=a[i]!;return o}
export function countBy<T>(a:Iterable<T>,fn:(v:T)=>PropertyKey):Record<PropertyKey,number>{const o=Object.create(null) as Record<PropertyKey,number>;for(const v of a){const k=fn(v);o[k]=(o[k]??0)+1}return o}
export function partition<T>(a:readonly T[],p:Predicate<T>):[T[],T[]]{const y:T[]=[],n:T[]=[];for(let i=0;i<a.length;i++)(p(a[i]!,i)?y:n).push(a[i]!);return[y,n]}
export function uniq<T>(a:readonly T[]):T[]{return [...new Set(a)]} export function uniqBy<T,K>(a:readonly T[],fn:(v:T)=>K):T[]{const s=new Set<K>(),o:T[]=[];for(const v of a){const k=fn(v);if(!s.has(k)){s.add(k);o.push(v)}}return o}
export function uniqWith<T>(a:readonly T[],eq:Comparator<T>):T[]{const o:T[]=[];outer:for(const v of a){for(const x of o)if(eq(v,x))continue outer;o.push(v)}return o}
export function difference<T>(a:readonly T[],b:readonly T[]):T[]{const s=new Set(b);return a.filter(v=>!s.has(v))} export function intersection<T>(a:readonly T[],b:readonly T[]):T[]{const s=new Set(b);return uniq(a.filter(v=>s.has(v)))}
export function union<T>(...xs:readonly (readonly T[])[]):T[]{const s=new Set<T>();for(const a of xs)for(const v of a)s.add(v);return[...s]}
export function without<T>(a:readonly T[],...values:T[]):T[]{return difference(a,values)} export function xor<T>(a:readonly T[],b:readonly T[]):T[]{return union(difference(a,b),difference(b,a))}
export function differenceBy<T,K>(a:readonly T[],b:readonly T[],fn:(v:T)=>K):T[]{const s=new Set(b.map(fn));return a.filter(v=>!s.has(fn(v)))}
export function intersectionBy<T,K>(a:readonly T[],b:readonly T[],fn:(v:T)=>K):T[]{const s=new Set(b.map(fn));return uniqBy(a.filter(v=>s.has(fn(v))),fn)}
export function unionBy<T,K>(a:readonly T[],b:readonly T[],fn:(v:T)=>K):T[]{return uniqBy([...a,...b],fn)} export function xorBy<T,K>(a:readonly T[],b:readonly T[],fn:(v:T)=>K):T[]{return unionBy(differenceBy(a,b,fn),differenceBy(b,a,fn),fn)}
function withCmp<T>(a:readonly T[],b:readonly T[],eq:Comparator<T>,mode:'diff'|'inter'):T[]{return a.filter(v=>(b.some(x=>eq(v,x)))===(mode==='inter'))}
export function differenceWith<T>(a:readonly T[],b:readonly T[],eq:Comparator<T>):T[]{return withCmp(a,b,eq,'diff')} export function intersectionWith<T>(a:readonly T[],b:readonly T[],eq:Comparator<T>):T[]{return uniqWith(withCmp(a,b,eq,'inter'),eq)}
export function unionWith<T>(a:readonly T[],b:readonly T[],eq:Comparator<T>):T[]{return uniqWith([...a,...b],eq)} export function xorWith<T>(a:readonly T[],b:readonly T[],eq:Comparator<T>):T[]{return unionWith(differenceWith(a,b,eq),differenceWith(b,a,eq),eq)}
export function isSubset<T>(a:readonly T[],b:readonly T[]):boolean{const s=new Set(b);for(const v of a)if(!s.has(v))return false;return true} export function isSubsetWith<T>(a:readonly T[],b:readonly T[],eq:Comparator<T>):boolean{return a.every(v=>b.some(x=>eq(v,x)))}
export function fill<T>(a:T[],v:T,start=0,end=a.length):T[]{for(let i=start;i<end;i++)a[i]=v;return a} export function toFilled<T>(a:readonly T[],v:T,start=0,end=a.length):T[]{return fill(a.slice(),v,start,end)}
export function pull<T>(a:T[],...vs:T[]):T[]{const s=new Set(vs);let w=0;for(let r=0;r<a.length;r++)if(!s.has(a[r]!))a[w++]=a[r]!;a.length=w;return a} export function pullAt<T>(a:T[],idx:readonly number[]):T[]{const s=new Set(idx),removed:T[]=[];for(const i of idx)if(i>=0&&i<a.length)removed.push(a[i]!);let w=0;for(let r=0;r<a.length;r++)if(!s.has(r))a[w++]=a[r]!;a.length=w;return removed}
export function remove<T>(a:T[],p:Predicate<T>):T[]{const out:T[]=[];let w=0;for(let r=0;r<a.length;r++){const v=a[r]!;if(p(v,r))out.push(v);else a[w++]=v}a.length=w;return out}
export function sample<T>(a:readonly T[]):T|undefined{return a.length?a[(Math.random()*a.length)|0]:undefined} export function sampleSize<T>(a:readonly T[],n=1):T[]{return shuffle(a.slice()).slice(0,n)} export function shuffle<T>(a:T[]):T[]{for(let i=a.length-1;i>0;i--){const j=(Math.random()*(i+1))|0;[a[i],a[j]]=[a[j]!,a[i]!]}return a}
export function maxBy<T>(a:readonly T[],fn:(v:T)=>number):T|undefined{let best=a[0],score=best===undefined?-Infinity:fn(best);for(let i=1;i<a.length;i++){const s=fn(a[i]!);if(s>score){score=s;best=a[i]}}return best} export function minBy<T>(a:readonly T[],fn:(v:T)=>number):T|undefined{return maxBy(a,v=>-fn(v))}
export function sortBy<T>(a:readonly T[],...fns:Array<(v:T)=>unknown>):T[]{return a.slice().sort((x,y)=>{for(const f of fns){const a=f(x),b=f(y);if(a<b)return-1;if(a>b)return 1}return 0})} export function orderBy<T>(a:readonly T[],fns:Array<(v:T)=>unknown>,orders:Array<'asc'|'desc'>=[]):T[]{return a.slice().sort((x,y)=>{for(let i=0;i<fns.length;i++){const av=fns[i]!(x),bv=fns[i]!(y),m=orders[i]==='desc'?-1:1;if(av<bv)return-m;if(av>bv)return m}return 0})}
export function cartesianProduct<T>(...arrays:readonly (readonly T[])[]):T[][]{let o:T[][]=[[]];for(const a of arrays){const n:T[][]=[];for(const p of o)for(const v of a)n.push([...p,v]);o=n}return o} export function combinations<T>(a:readonly T[],k:number):T[][]{const o:T[][]=[];function go(s:number,p:T[]){if(p.length===k){o.push(p.slice());return}for(let i=s;i<a.length;i++){p.push(a[i]!);go(i+1,p);p.pop()}}go(0,[]);return o}
export function windowed<T>(a:readonly T[],size:number,step=1):T[][]{const o:T[][]=[];for(let i=0;i+size<=a.length;i+=step)o.push(a.slice(i,i+size));return o}
export function zip<T>(...a:readonly (readonly T[])[]):T[][]{const n=Math.max(0,...a.map(x=>x.length)),o:T[][]=[];for(let i=0;i<n;i++)o.push(a.map(x=>x[i] as T));return o} export function unzip<T>(a:readonly (readonly T[])[]):T[][]{return zip(...a)} export function zipWith<T,R>(a:readonly T[],b:readonly T[],fn:(a:T|undefined,b:T|undefined)=>R):R[]{const n=Math.max(a.length,b.length),o:R[]=[];for(let i=0;i<n;i++)o.push(fn(a[i],b[i]));return o} export function unzipWith<T,R>(a:readonly (readonly T[])[],fn:(...v:T[])=>R):R[]{return unzip(a).map(v=>fn(...v))} export function zipObject<K extends PropertyKey,V>(k:readonly K[],v:readonly V[]):Record<K,V>{const o=Object.create(null);for(let i=0;i<k.length;i++)o[k[i]!]=v[i];return o}

/** Direct loop replacement for `Object.entries(obj).map(...)`. @remarks Avoids allocating `[key,value]` tuples, a meaningful win in allocation-sensitive Safari/WebKit hot paths. */
export function mapValues<T extends object,R>(obj:T,fn:(v:T[keyof T],k:keyof T)=>R):Record<keyof T,R>{const o={} as Record<keyof T,R>;for(const k in obj)if(Object.prototype.hasOwnProperty.call(obj,k))o[k as keyof T]=fn(obj[k as keyof T],k as keyof T);return o}
export function mapKeys<T extends object>(obj:T,fn:(v:T[keyof T],k:keyof T)=>PropertyKey):Record<PropertyKey,T[keyof T]>{const o:Record<PropertyKey,T[keyof T]>={};for(const k in obj)if(Object.prototype.hasOwnProperty.call(obj,k))o[fn(obj[k as keyof T],k as keyof T)]=obj[k as keyof T];return o}
/** Shallow clone optimized for plain enumerable records. @remarks Replaces `{...obj}`/`Object.assign` in hot generic paths while preserving symbols through `Reflect.ownKeys`. */
export function clone<T>(v:T):T{if(Array.isArray(v))return v.slice() as T;if(v&&typeof v==='object'){const o=Object.create(Object.getPrototypeOf(v));for(const k of Reflect.ownKeys(v as object))if(Object.prototype.propertyIsEnumerable.call(v,k))o[k]=(v as any)[k];return o}return v}
/** Deep clone with cycle handling. @remarks Replaces JSON stringify/parse, preserving Date, RegExp, Map, Set, typed arrays and cycles. Uses a WeakMap so repeated references remain shared. */
export function cloneDeep<T>(v:T,seen=new WeakMap<object,unknown>()):T{if(!v||typeof v!=='object')return v;if(seen.has(v as object))return seen.get(v as object) as T;if(v instanceof Date)return new Date(v) as T;if(v instanceof RegExp)return new RegExp(v.source,v.flags) as T;if(v instanceof Map){const o=new Map();seen.set(v,o);for(const[k,x]of v)o.set(cloneDeep(k,seen),cloneDeep(x,seen));return o as T}if(v instanceof Set){const o=new Set();seen.set(v,o);for(const x of v)o.add(cloneDeep(x,seen));return o as T}if(ArrayBuffer.isView(v))return new (v.constructor as any)(v as any) as T;if(v instanceof ArrayBuffer)return v.slice(0) as T;const o:any=Array.isArray(v)?[]:Object.create(Object.getPrototypeOf(v));seen.set(v as object,o);for(const k of Reflect.ownKeys(v as object))o[k]=cloneDeep((v as any)[k],seen);return o}
export function cloneDeepWith<T>(v:T,custom:(v:unknown)=>unknown):T{const x=custom(v);return (x===undefined?cloneDeep(v):x) as T}
export function pick<T extends object,K extends keyof T>(o:T,keys:readonly K[]):Pick<T,K>{const r={} as Pick<T,K>;for(const k of keys)if(k in o)r[k]=o[k];return r} export function omit<T extends object,K extends keyof T>(o:T,keys:readonly K[]):Omit<T,K>{const s=new Set<PropertyKey>(keys),r:any={};for(const k of Reflect.ownKeys(o))if(!s.has(k))r[k]=(o as any)[k];return r}
export function pickBy<T extends object>(o:T,p:(v:T[keyof T],k:keyof T)=>unknown):Partial<T>{const r:Partial<T>={};for(const k in o)if(Object.hasOwn(o,k)&&p(o[k as keyof T],k as keyof T))r[k as keyof T]=o[k as keyof T];return r} export function omitBy<T extends object>(o:T,p:(v:T[keyof T],k:keyof T)=>unknown):Partial<T>{return pickBy(o,(v,k)=>!p(v,k))}
export function invert(o:Record<PropertyKey,PropertyKey>):Record<PropertyKey,PropertyKey>{const r:Record<PropertyKey,PropertyKey>={};for(const k of Reflect.ownKeys(o))r[o[k]!]=k;return r} export function sortKeys<T extends object>(o:T):Partial<T>{const r:Partial<T>={};for(const k of Object.keys(o).sort())(r as any)[k]=(o as any)[k];return r}
export function flattenObject(o:Record<string,unknown>,prefix='',r:Record<string,unknown>={}):Record<string,unknown>{for(const k in o){const key=prefix?prefix+'.'+k:k,v=o[k];if(isPlainObject(v))flattenObject(v as Record<string,unknown>,key,r);else r[key]=v}return r}
export function merge<T extends object>(target:T,...sources:object[]):T{for(const s of sources)for(const k of Reflect.ownKeys(s)){const sv=(s as any)[k],tv=(target as any)[k];(target as any)[k]=isPlainObject(sv)&&isPlainObject(tv)?merge(tv,sv):cloneDeep(sv)}return target} export function mergeWith<T extends object>(target:T,source:object,fn:(a:unknown,b:unknown,k:PropertyKey)=>unknown):T{for(const k of Reflect.ownKeys(source)){const x=fn((target as any)[k],(source as any)[k],k);(target as any)[k]=x===undefined?(source as any)[k]:x}return target} export function toMerged<T extends object>(target:T,...s:object[]):T{return merge(cloneDeep(target),...s)}

export const isNil=(v:unknown):v is null|undefined=>v==null; export const isNotNil=<T>(v:T):v is NonNullable<T>=>v!=null; export const isNull=(v:unknown):v is null=>v===null; export const isUndefined=(v:unknown):v is undefined=>v===undefined; export const isBoolean=(v:unknown):v is boolean=>typeof v==='boolean'; export const isNumber=(v:unknown):v is number=>typeof v==='number'&&!Number.isNaN(v); export const isString=(v:unknown):v is string=>typeof v==='string'; export const isSymbol=(v:unknown):v is symbol=>typeof v==='symbol'; export const isFunction=(v:unknown):v is Function=>typeof v==='function'; export const isPrimitive=(v:unknown)=>v==null||(typeof v!=='object'&&typeof v!=='function'); export const isDate=(v:unknown):v is Date=>v instanceof Date; export const isRegExp=(v:unknown):v is RegExp=>v instanceof RegExp; export const isMap=(v:unknown):v is Map<unknown,unknown>=>v instanceof Map; export const isSet=(v:unknown):v is Set<unknown>=>v instanceof Set; export const isWeakMap=(v:unknown):v is WeakMap<object,unknown>=>v instanceof WeakMap; export const isWeakSet=(v:unknown):v is WeakSet<object>=>v instanceof WeakSet; export const isPromise=(v:any):v is PromiseLike<unknown>=>!!v&&(typeof v==='object'||typeof v==='function')&&typeof v.then==='function'; export const isIterable=(v:any):v is Iterable<unknown>=>v!=null&&typeof v[Symbol.iterator]==='function'; export const isArrayBuffer=(v:unknown):v is ArrayBuffer=>v instanceof ArrayBuffer; export const isTypedArray=(v:unknown):v is ArrayBufferView=>ArrayBuffer.isView(v)&&!(v instanceof DataView); export const isError=(v:unknown):v is Error=>v instanceof Error; export const isPlainObject=(v:unknown):v is Record<PropertyKey,unknown>=>{if(v===null||typeof v!=='object')return false;const p=Object.getPrototypeOf(v);return p===null||p===Object.prototype}; export const isEmptyObject=(v:unknown)=>isPlainObject(v)&&Reflect.ownKeys(v).length===0; export const isLength=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>=0; export const isBrowser=()=>typeof window!=='undefined'&&typeof document!=='undefined'; export const isNode=()=>typeof process!=='undefined'&&!!process.versions?.node; export const isBlob=(v:unknown):v is Blob=>typeof Blob!=='undefined'&&v instanceof Blob; export const isFile=(v:unknown):v is File=>typeof File!=='undefined'&&v instanceof File; export const isBuffer=(v:unknown)=>typeof Buffer!=='undefined'&&Buffer.isBuffer(v);
export function isEqual(a:unknown,b:unknown):boolean{if(Object.is(a,b))return true;if(!a||!b||typeof a!=='object'||typeof b!=='object')return false;if(a instanceof Date&&b instanceof Date)return +a===+b;if(Array.isArray(a)&&Array.isArray(b)){if(a.length!==b.length)return false;for(let i=0;i<a.length;i++)if(!isEqual(a[i],b[i]))return false;return true}const ak=Reflect.ownKeys(a),bk=Reflect.ownKeys(b);if(ak.length!==bk.length)return false;for(const k of ak)if(!Object.hasOwn(b,k)||!isEqual((a as any)[k],(b as any)[k]))return false;return true} export function isEqualWith(a:unknown,b:unknown,fn:(a:unknown,b:unknown)=>boolean|undefined):boolean{return fn(a,b)??isEqual(a,b)}
export function isJSON(v:string):boolean{try{JSON.parse(v);return true}catch{return false}} export function isJSONValue(v:unknown):boolean{if(v===null||['string','boolean'].includes(typeof v)||isNumber(v))return true;if(Array.isArray(v))return v.every(isJSONValue);if(isPlainObject(v))return Object.values(v).every(isJSONValue);return false} export const isJSONArray=(v:unknown)=>Array.isArray(v)&&isJSONValue(v); export const isJSONObject=(v:unknown)=>isPlainObject(v)&&isJSONValue(v);

export const clamp=(n:number,min:number,max:number)=>n<min?min:n>max?max:n; export const inRange=(n:number,start:number,end=0)=>{if(start>end)[start,end]=[end,start];return n>=start&&n<end}; export function sum(a:readonly number[]):number{let n=0;for(let i=0;i<a.length;i++)n+=a[i]!;return n} export function sumBy<T>(a:readonly T[],fn:(v:T)=>number):number{let n=0;for(let i=0;i<a.length;i++)n+=fn(a[i]!);return n} export const mean=(a:readonly number[])=>a.length?sum(a)/a.length:NaN; export const meanBy=<T>(a:readonly T[],f:(v:T)=>number)=>a.length?sumBy(a,f)/a.length:NaN; export function median(a:readonly number[]):number{if(!a.length)return NaN;const x=a.slice().sort((a,b)=>a-b),m=x.length>>1;return x.length%2?x[m]!:(x[m-1]!+x[m]!)/2} export const medianBy=<T>(a:readonly T[],f:(v:T)=>number)=>median(a.map(f)); export function percentile(a:readonly number[],p:number):number{if(!a.length)return NaN;const x=a.slice().sort((a,b)=>a-b),i=clamp(p,0,1)*(x.length-1),lo=Math.floor(i),hi=Math.ceil(i),t=i-lo;return x[lo]!*(1-t)+x[hi]!*t} export const random=(min=0,max=1)=>min+Math.random()*(max-min); export const randomInt=(min:number,max:number)=>Math.floor(random(min,max+1)); export function range(start:number,end?:number,step=1):number[]{if(end===undefined){end=start;start=0}const o:number[]=[];if(step>0)for(let i=start;i<end;i+=step)o.push(i);else for(let i=start;i>end;i+=step)o.push(i);return o} export function rangeRight(...a:Parameters<typeof range>):number[]{return range(...a).reverse()} export const round=(n:number,p=0)=>{const f=10**p;return Math.round((n+Number.EPSILON)*f)/f};

export const identity=<T>(v:T)=>v; export const noop=()=>{}; export const asyncNoop=async()=>{}; export function once<F extends(...a:any[])=>any>(fn:F):F{let done=false,v:any;return function(this:any,...a:any[]){if(!done){done=true;v=fn.apply(this,a)}return v} as F} export function before<F extends(...a:any[])=>any>(n:number,fn:F):F{let c=0,v:any;return function(this:any,...a:any[]){if(++c<n)v=fn.apply(this,a);return v} as F} export function after<F extends(...a:any[])=>any>(n:number,fn:F):F{let c=0;return function(this:any,...a:any[]){if(++c>=n)return fn.apply(this,a)} as F} export const unary=<F extends(a:any,...x:any[])=>any>(fn:F)=>(a:Parameters<F>[0])=>fn(a); export const ary=<F extends(...a:any[])=>any>(fn:F,n:number)=>(...a:any[])=>fn(...a.slice(0,n)); export const negate=<F extends(...a:any[])=>any>(fn:F)=>(...a:Parameters<F>)=>!fn(...a); export const rest=<F extends(...a:any[])=>any>(fn:F,start=fn.length-1)=>(...a:any[])=>fn(...a.slice(0,start),a.slice(start)); export const spread=<F extends(...a:any[])=>any>(fn:F)=>(a:Parameters<F>)=>fn(...a); export const partial=<F extends(...a:any[])=>any>(fn:F,...p:any[])=>(...a:any[])=>fn(...p,...a); export const partialRight=<F extends(...a:any[])=>any>(fn:F,...p:any[])=>(...a:any[])=>fn(...a,...p); export const flow=(...f:Array<(x:any)=>any>)=>(x:any)=>f.reduce((v,fn)=>fn(v),x); export const flowRight=(...f:Array<(x:any)=>any>)=>flow(...f.reverse()); export function memoize<F extends(...a:any[])=>any>(fn:F,key=(...a:Parameters<F>)=>a[0]):F{const c=new Map();return function(this:any,...a:any[]){const k=key(...a as Parameters<F>);if(c.has(k))return c.get(k);const v=fn.apply(this,a);c.set(k,v);return v} as F}
export function debounce<F extends(...a:any[])=>any>(fn:F,wait=0){let t:ReturnType<typeof setTimeout>|undefined;const f=(...a:Parameters<F>)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),wait)};f.cancel=()=>clearTimeout(t);return f} export function throttle<F extends(...a:any[])=>any>(fn:F,wait=0){let last=0,t:ReturnType<typeof setTimeout>|undefined;return(...a:Parameters<F>)=>{const now=Date.now(),left=wait-(now-last);if(left<=0){last=now;fn(...a)}else if(!t)t=setTimeout(()=>{t=undefined;last=Date.now();fn(...a)},left)}}
export async function retry<T>(fn:()=>Awaitable<T>,times=3,delayMs=0):Promise<T>{let e:unknown;for(let i=0;i<times;i++)try{return await fn()}catch(x){e=x;if(delayMs)await delay(delayMs)}throw e} export function curry(fn:Function,arity=fn.length):any{const next=(a:any[]):any=>a.length>=arity?fn(...a):(...b:any[])=>next([...a,...b]);return next([])} export function curryRight(fn:Function,arity=fn.length):any{return curry((...a:any[])=>fn(...a.reverse()),arity)}

export class AbortError extends Error{name='AbortError';constructor(message='Operation aborted'){super(message)}} export class TimeoutError extends Error{name='TimeoutError';constructor(message='Operation timed out'){super(message)}}
export const delay=(ms:number,signal?:AbortSignal)=>new Promise<void>((resolve,reject)=>{if(signal?.aborted)return reject(new AbortError());const t=setTimeout(resolve,ms);signal?.addEventListener('abort',()=>{clearTimeout(t);reject(new AbortError())},{once:true})}); export function timeout(ms:number,signal?:AbortSignal):Promise<never>{return new Promise((_,reject)=>{const t=setTimeout(()=>reject(new TimeoutError()),ms);signal?.addEventListener('abort',()=>{clearTimeout(t);reject(new AbortError())},{once:true})})} export async function withTimeout<T>(p:Awaitable<T>,ms:number):Promise<T>{return Promise.race([p,timeout(ms)])} export async function allKeyed<T extends Record<PropertyKey,Awaitable<any>>>(o:T):Promise<{[K in keyof T]:Awaited<T[K]>}>{const keys=Reflect.ownKeys(o) as (keyof T)[],vals=await Promise.all(keys.map(k=>o[k]));const r:any={};for(let i=0;i<keys.length;i++)r[keys[i]]=vals[i];return r}
export class Semaphore{private q:Array<()=>void>=[];constructor(public permits=1){}async acquire(){if(this.permits>0){this.permits--;return}await new Promise<void>(r=>this.q.push(r))}release(){const n=this.q.shift();n?n():this.permits++}async use<T>(fn:()=>Awaitable<T>):Promise<T>{await this.acquire();try{return await fn()}finally{this.release()}}} export class Mutex extends Semaphore{constructor(){super(1)}}

export function mapMap<K,V,R>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>R):Map<K,R>{const o=new Map<K,R>();for(const[k,v]of m)o.set(k,fn(v,k));return o} export function filterMap<K,V>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>unknown):Map<K,V>{const o=new Map<K,V>();for(const[k,v]of m)if(fn(v,k))o.set(k,v);return o} export function mapKeysMap<K,V,R>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>R):Map<R,V>{const o=new Map<R,V>();for(const[k,v]of m)o.set(fn(v,k),v);return o} export function mapValuesMap<K,V,R>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>R):Map<K,R>{return mapMap(m,fn)} export function reduceMap<K,V,R>(m:ReadonlyMap<K,V>,fn:(a:R,v:V,k:K)=>R,a:R):R{for(const[k,v]of m)a=fn(a,v,k);return a} export function everyMap<K,V>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>unknown):boolean{for(const[k,v]of m)if(!fn(v,k))return false;return true} export function someMap<K,V>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>unknown):boolean{for(const[k,v]of m)if(fn(v,k))return true;return false} export function findKeyMap<K,V>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>unknown):K|undefined{for(const[k,v]of m)if(fn(v,k))return k} export function findValueMap<K,V>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>unknown):V|undefined{for(const[k,v]of m)if(fn(v,k))return v} export function hasValue<K,V>(m:ReadonlyMap<K,V>,x:V):boolean{for(const v of m.values())if(Object.is(v,x))return true;return false} export function forEachMap<K,V>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>void):void{for(const[k,v]of m)fn(v,k)} export function keyByMap<K,V,R>(m:ReadonlyMap<K,V>,fn:(v:V,k:K)=>R):Map<R,V>{const o=new Map<R,V>();for(const[k,v]of m)o.set(fn(v,k),v);return o}
export function mapSet<T,R>(s:ReadonlySet<T>,fn:(v:T)=>R):Set<R>{const o=new Set<R>();for(const v of s)o.add(fn(v));return o} export function filterSet<T>(s:ReadonlySet<T>,fn:(v:T)=>unknown):Set<T>{const o=new Set<T>();for(const v of s)if(fn(v))o.add(v);return o} export function reduceSet<T,R>(s:ReadonlySet<T>,fn:(a:R,v:T)=>R,a:R):R{for(const v of s)a=fn(a,v);return a} export function everySet<T>(s:ReadonlySet<T>,fn:(v:T)=>unknown):boolean{for(const v of s)if(!fn(v))return false;return true} export function someSet<T>(s:ReadonlySet<T>,fn:(v:T)=>unknown):boolean{for(const v of s)if(fn(v))return true;return false} export function findSet<T>(s:ReadonlySet<T>,fn:(v:T)=>unknown):T|undefined{for(const v of s)if(fn(v))return v} export function forEachSet<T>(s:ReadonlySet<T>,fn:(v:T)=>void):void{for(const v of s)fn(v)} export function keyBySet<T,K>(s:ReadonlySet<T>,fn:(v:T)=>K):Map<K,T>{const o=new Map<K,T>();for(const v of s)o.set(fn(v),v);return o}

const WORDS=/[A-Z]?[a-z]+|[A-Z]+(?![a-z])|\d+/g; export const words=(s:string)=>s.match(WORDS)??[]; export const deburr=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,''); export const capitalize=(s:string)=>s?upperFirst(s.toLowerCase()):s; export const upperFirst=(s:string)=>s?s[0]!.toUpperCase()+s.slice(1):s; export const lowerFirst=(s:string)=>s?s[0]!.toLowerCase()+s.slice(1):s; export const camelCase=(s:string)=>{const w=words(deburr(s));return w.map((x,i)=>i?capitalize(x):x.toLowerCase()).join('')}; export const pascalCase=(s:string)=>words(deburr(s)).map(capitalize).join(''); export const kebabCase=(s:string)=>words(deburr(s)).map(x=>x.toLowerCase()).join('-'); export const snakeCase=(s:string)=>words(deburr(s)).map(x=>x.toLowerCase()).join('_'); export const constantCase=(s:string)=>snakeCase(s).toUpperCase(); export const startCase=(s:string)=>words(deburr(s)).map(capitalize).join(' '); export const lowerCase=(s:string)=>words(deburr(s)).join(' ').toLowerCase(); export const upperCase=(s:string)=>words(deburr(s)).join(' ').toUpperCase(); export const reverseString=(s:string)=>Array.from(s).reverse().join(''); export const pad=(s:string,n:number,c=' ')=>(c.repeat(Math.max(0,Math.floor((n-s.length)/2)))+s+c.repeat(Math.max(0,Math.ceil((n-s.length)/2)))).slice(0,n); export const trim=(s:string,c?:string)=>c?trimEnd(trimStart(s,c),c):s.trim(); export const trimStart=(s:string,c?:string)=>c?s.replace(new RegExp('^'+escapeRegExp(c)+'+'),''):s.trimStart(); export const trimEnd=(s:string,c?:string)=>c?s.replace(new RegExp(escapeRegExp(c)+'+$'),''):s.trimEnd(); export const escapeRegExp=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); const HTML:Record<string,string>={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}; export const escape=(s:string)=>s.replace(/[&<>"']/g,c=>HTML[c]!); export const unescape=(s:string)=>s.replace(/&(amp|lt|gt|quot|#39);/g,x=>Object.entries(HTML).find(([,v])=>v===x)?.[0]??x);
export function toCamelCaseKeys<T>(v:T):T{return transformKeys(v,camelCase)} export function toSnakeCaseKeys<T>(v:T):T{return transformKeys(v,snakeCase)} function transformKeys(v:any,fn:(s:string)=>string):any{if(Array.isArray(v))return v.map(x=>transformKeys(x,fn));if(isPlainObject(v)){const o:any={};for(const k in v)o[fn(k)]=transformKeys(v[k],fn);return o}return v}

export function assert(condition:unknown,message='Assertion failed'):asserts condition{if(!condition)throw new Error(message)} export function invariant(condition:unknown,message='Invariant violation'):asserts condition{assert(condition,message)} export function attempt<T>(fn:()=>T):[T,null]|[undefined,unknown]{try{return[fn(),null]}catch(e){return[undefined,e]}} export async function attemptAsync<T>(fn:()=>Awaitable<T>):Promise<[T,null]|[undefined,unknown]>{try{return[await fn(),null]}catch(e){return[undefined,e]}}
