name: 📦🐳 Publish DevTools

on:
  workflow_dispatch:
    inputs:
      release_channel:
        type: choice
        description: "Publish until"
        default: canary
        options:
          - canary
          - production
          - both
      test_mode:
        type: choice
        description: "Tests"
        default: auto
        options:
          - auto
          - always
          - never
      should_typecheck:
        type: boolean
        description: "Run typecheck?"
        default: true
      should_benchmark:
        type: boolean
        description: "Run benchmarks?"
        default: false
      should_deploy_pages:
        type: boolean
        description: "Deploy to GitHub Pages?"
        default: true
      force_clean_deploy:
        type: boolean
        description: "Delete previous published files first?"
        default: false

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
  pull-requests: read


jobs:
  publish:
    name: 🐳 Reuse browser publisher
    uses: ./.github/workflows/publish-browser-bundle.yml
    with:
      project: devtools
      release_channel: ${{ inputs.release_channel }}
      test_mode: ${{ inputs.test_mode }}
      should_typecheck: ${{ inputs.should_typecheck }}
      should_benchmark: ${{ inputs.should_benchmark }}
      should_deploy_pages: ${{ inputs.should_deploy_pages }}
      force_clean_deploy: ${{ inputs.force_clean_deploy }}
    secrets: inherit
